# Generated by Django 4.2.2 on 2023-06-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fytoken', models.CharField(max_length=255, unique=True)),
                ('symbol_details', models.CharField(max_length=255)),
                ('exchange_instrument_type', models.IntegerField()),
                ('minimum_lot_size', models.IntegerField()),
                ('tick_size', models.FloatField()),
                ('isin', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_session', models.CharField(max_length=255)),
                ('last_update_date', models.DateField()),
                ('expiry_date', models.CharField(max_length=255)),
                ('symbol_ticker', models.CharField(max_length=255)),
                ('exchange', models.IntegerField()),
                ('segment', models.IntegerField()),
                ('scrip_code', models.IntegerField()),
                ('underlying_scrip_code', models.CharField(max_length=200)),
                ('modifed_script_code', models.IntegerField()),
                ('strike_price', models.FloatField()),
                ('option_type', models.CharField(max_length=255)),
                ('exchange_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquitySymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fytoken', models.CharField(max_length=255, unique=True)),
                ('symbol_details', models.CharField(max_length=255)),
                ('exchange_instrument_type', models.IntegerField()),
                ('minimum_lot_size', models.IntegerField()),
                ('tick_size', models.FloatField()),
                ('isin', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_session', models.CharField(max_length=255)),
                ('last_update_date', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(max_length=255)),
                ('symbol_ticker', models.CharField(max_length=255)),
                ('exchange', models.IntegerField()),
                ('segment', models.IntegerField()),
                ('scrip_code', models.IntegerField()),
                ('underlying_scrip_code', models.CharField(max_length=200)),
                ('modifed_script_code', models.IntegerField()),
                ('strike_price', models.FloatField()),
                ('option_type', models.CharField(max_length=255)),
                ('exchange_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MCXSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fytoken', models.CharField(max_length=255, unique=True)),
                ('symbol_details', models.CharField(max_length=255)),
                ('exchange_instrument_type', models.IntegerField()),
                ('minimum_lot_size', models.IntegerField()),
                ('tick_size', models.FloatField()),
                ('isin', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_session', models.CharField(max_length=255)),
                ('last_update_date', models.DateField()),
                ('expiry_date', models.CharField(max_length=255)),
                ('symbol_ticker', models.CharField(max_length=255)),
                ('exchange', models.IntegerField()),
                ('segment', models.IntegerField()),
                ('scrip_code', models.IntegerField()),
                ('underlying_scrip_code', models.CharField(max_length=200)),
                ('modifed_script_code', models.IntegerField()),
                ('strike_price', models.FloatField()),
                ('option_type', models.CharField(max_length=255)),
                ('exchange_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fyers_Auth_Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('secret_id', models.CharField(blank=True, max_length=50, null=True)),
                ('redirect_url', models.CharField(default='https://trade.fyers.in/api-login/redirect-uri/index.html', max_length=100)),
                ('user_ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fyers_Access_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=1500, null=True)),
                ('app_ass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.fyers_auth_inputs')),
            ],
        ),
    ]
